---
title: "Data Types"
format: html
editor: visual
---


#| warning: false
#| echop: false


```{r, include = FALSE}

#| include: false
#| warning: false
#| echo: false

library(tidyverse)
library(palmerpenguins)
library(GGally)
library(skimr)
```

## Exploratory Data Viz

# Check out your data a bit:

```{r}
# Tell me the column names
names(penguins)


# What are the dimensions?
dim(penguins)

# Can you show me the first 6 lines?
head(penguins)

# Can you show me the last 6 lines?
tail(penguins)

class(penguins)
```


```{r}
skim(penguins)
```

```{r}
# GG ally
#| include: false

GGally::ggpairs(penguins)
```


##Jitterplot

Flipper length by species

```{r}
ggplot(data=penguins, aes(x = species, y = flipper_length_mm)) +
  geom_jitter(aes(color=species),
              width = .2,
              alpha = 0.5) +
  geom_boxplot(fill = NA) +
  theme_light() +
  scale_color_manual(values = c("darkorchid4", "cyan4", "goldenrod")) + 
  labs(x= "Species", y= "Flipper Length (mm)", tittle = "Penguins Graph")

```



```{r}


ggplot(data=penguins, aes(x= bill_length_mm)) +
  geom_histogram(aes(fill = species), color = "magenta") + 
  facet_wrap(~species, ncol = 1)
```

